name: First workflow
on: workflow_dispatch #makes sure we can manually trigger workflow if we want to

jobs: 
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello world"
        
      - name: Print goodbue
        run: echo "Done, goodbye"
      
